[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@morpho-blue/=lib/morpho-blue/",
    "@erc6909/=lib/erc6909/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
polygon = "https://polygon-rpc.com"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
